Build started...
Build succeeded.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE users (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NIK" character varying(450) NOT NULL,
    "Nama" character varying(200) NOT NULL DEFAULT '',
    "TTL" character varying(200) NOT NULL DEFAULT '',
    "Alamat" character varying(500) NOT NULL DEFAULT '',
    "NoTelp" character varying(20) NOT NULL DEFAULT '',
    "PasswordHash" bytea NOT NULL,
    "PasswordSalt" bytea NOT NULL,
    "UserType" character varying(10) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_users_nik" ON users ("NIK");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250616125553_InitialPostgreSQLMigration', '9.0.4');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250616133607_InitialMigration', '9.0.4');

COMMIT;


